### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bs34**

### CODE REVIEW

**Comment by jGleitz** [comment]
@bs34, you joined GitHub just today and opened various pull requests on completely unrelated repositories. All contain only such small changes. Are you human? Are you actually trying to help or just trying to collect credibility, or something like that?

**Comment by bs34** [comment]
I have been told to be active on GitHub from my college professors.

On 31-Oct-2017 7:18 PM, "Joshua Gleitze" <notifications@github.com> wrote:

@bs34 <https://github.com/bs34>, you joined GitHub just today and opened
various pull requests on completely unrelated repositories. All contain
only such small changes. Are you human? Are you actually trying to help or
just trying to collect credibility, or something like that?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vitruv-tools/Vitruv/pull/179#issuecomment-340767365>,
or mute the thread

**Comment by HeikoKlare** [comment]
Thank you @jGleitz for responding to this request.

@bs34: If you have to be active on GitHub, please make useful contributions instead of modifying our readme file. You will not get any credits for such modifications.

**Comment by HeikoKlare** [comment]
@bs34: In addition, you will now be blocked from our organization. Do not try to _be active_ on our or associate organizations again, or otherwise I will make a report.

**Pull request closed without merging**
